### ISSUE TITLE
Do we really need to install @tanstack/vue-query separately? 

### ISSUE THREAD

**Issue by aleksdotbar** [ozum/nuxt-vue-query#1]
Hi! Nice work here.

But shouldn't it just work with the module installed?

**Comment by ozum** [comment]
I should have added `@tanstack/vue-query` into peer dependencies, so you could use new versions of `@tanstack/vue-query` as it is released.

I've moved it to the peer deps.

@xanderbarkhatov, could you please install both `@tanstack/vue-query` and `nuxt-vue-query` and test it is ok?

**Comment by aleksdotbar** [comment]
I'm not sure if it works correctly.
For some reason request fires twice (on server and on client) when using SSR. It's fine when I use just the plugin from the official docs, although your plugin seems identical.

**Comment by ozum** [comment]
Hi @xanderbarkhatov. If there was a problem related to `peer dependencies` it shouldn't work.

The double request may be related to the configuration.
